# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: setup git auth
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USER }}
          access_token: ${{ secrets.VUEJS_ACCESS_TOKEN }}
        run: |
          echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config user.email $email
          git config user.name $username
      - name: deploy to gh-pages
        run: |
          npm i
          NODE_ENV=production npm run build
          cd dist
          git init
          git add -A
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
          git push -f "https://github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
